services:
  postgres:
    container_name: nextjs_admin_template_postgres
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nextjs_admin_template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=admin --dbname=nextjs_admin_template" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
